### ISSUE TITLE
Going into Nether Portal teleports to the End

### ISSUE THREAD

**Issue by drjawa** [Civcraft/FactoryMod#24]
This might not be due to Factorymod, but no other idea where to put it.

Regardless of whether I am in creative or survlval or in the nether or overworld, going into a nether portal sends me to the end.

Is this intention behavior?

**Summary**:
Player must be an OP
Player must also be pearled.
Works in the nether and in the overworld

**Comment by gipsy-king** [comment]
Seems to be this line: https://github.com/Civcraft/PrisonPearl/blob/master/src/com/untamedears/PrisonPearl/PrisonPearlPlugin.java#L467
To me it looks like this is written for a pearled player entering the end portal from the end, and this will send him back to the end. That is, checking that he is imprisoned and not summoned is enough, it can only be the end portal because there are no nether portals in the end. Except if the player managed to move to overworld with OP commands, where Jawa could indeed touch a nether portal while technically being imprisoned and not summoned.

I think this bug can be closed unless someone wants to add a clause for this particular OP edge case.

**Comment by ttk2** [comment]
I don't think we need to catch this
