### ISSUE TITLE
Suggested improvements to Fancy Stone Brick Smelter

### ISSUE THREAD

**Issue by CodingMonkeyXYZ** [Civcraft/FactoryMod#42]
It does seem rather pointless to make nice decorative bricks so overly expensive, given they have no other benefit other than making the server look a little nicer. Also the ratio of 64 fancy bricks for 64 plain bricks and a few odds and ends like flint seems a bit unfair. Let's get something back for our lapis investment in making the factory, why not make the factory worth your while and double your fancy stone brick output? 

I suggest altering the recipes by removing the lapis requirement for smelting and doubling the fancy brick output. Keep the lapis requirement for making the factory if you like - that makes some sense, if the output is increased.

**Comment by ttk2** [comment]
I need to look up why it was designed like this in the first place, I feel
like someone had a point in doing this.

**Comment by jjj5311** [comment]
to give lapis more value and make it used in something

**Comment by ac7web** [comment]
Sure, that made sense back when we didn't use it for all kinds of expensive factories but not now.

**Comment by ProgrammerDan** [comment]
@MagicalMonkey What kind of rebalance did you have in mind?

**Comment by MagicalMonkey** [comment]
Well originally: removing the lapis requirement for smelting and doubling the fancy brick output. Keep the lapis requirement for making the factory and repairing it.

**Comment by ProgrammerDan** [comment]
I can't speak for the admins but it'd make more sense to simply enable the crafting recipe then to eliminate the cost factor, if we want to go that route.

Do you [use the discourse?](forum.civcraft.co) This sounds like a great question for the [Development Balance category](https://forum.civcraft.co/c/development/balance-and-rules-discussion). 

I haven't *generally* heard complaints, but given the very few people who actively use the factory (I think in Mount Augusta it is being used now *only* because of Bastions) and the even fewer people leveraging those stone types in their builds, you've got a good case. I might find the following recipe a good halfway point:

64 stone brick, 16 lapis, 64 gravel for 96 chiseled stone brick.

For the other stone brick types, also bumping them to 96 and cutting lapis requirement in half. 

That might reduce the barrier to entry just enough to encourage use without eliminating the purpose of having them as a factory recipe, which is what removing the lapis requirement entirely would do.

**Comment by Maxopoly** [comment]
Not relevant anymore, because the old config wont be used anymore
