### ISSUE TITLE
Printing Press code doesn't allow for <1 of something per book recipes

### ISSUE THREAD

**Issue by GavJenks** [Civcraft/FactoryMod#45]
...which is necessary if we are going to change the recipes to be cheaper than simply hand crafting. Unfortunately this requires a code rewrite, therefore, to make book printing reasonable. Not  just config options.

Not a "bug" but a feature that would be necessary to get this factory used for books.

Alternatively, we could just ditch the complicated printing press concept entirely, and replace it with a very simple normal factory that has simple, fixed cost, fixed batch size recipes for plates, pamphlets, books, and notes. Just like every other normal factory. Which I actually think is by far the best solution here. There is really no reason for it to be different and 10x more complicated than other factories, other than the detail of adding the lore for plates.

**Comment by ttk2** [comment]
I am afraid I have to agree with moving to a more normal structure, what
about security notes though?

**Comment by GavJenks** [comment]
Security notes can use a normal factory, too. Nothing about them requires continuous weird / delayed / multibatch thingies.

It requires one or two lines of code to invent a number and stick it at the end of the lore for them (and books IIRC?) when making prints, but that is all.

**Comment by ttk2** [comment]
Agreed then. Converting existing presses should not be too bad.

**Comment by WildWeazel** [comment]
I agree, the current Printing Press model is too complex to maintain and makes too many assumptions about how they should work (You can't even disabled them without code changes FWIW). A regular factory using lore should do just fine.

**Comment by staygroovy57** [comment]
Sorry for being late with this, but have been busy IRL. One thing that the securities note feature was providing us with was the relative impossibility for notes to be forged by first using a 'Master Template' which had an embedded randomized number between '0000' and '9999' ... All identical notes could then only be crafted using this 'printing plate' master as a source. 

If you change the way these securities notes are crafted make sure that they retain the same features so that it prevents counterfeiting. Securities notes are currently used for in-game currency and Nether Factory one-time passes, both of which would suffer greatly if this number can somehow be forged/duplicated.

**Comment by ttk2** [comment]
its only 1/10000 chance of forgery? that's less than I thought

**Comment by ProgrammerDan** [comment]
> its only 1/10000 chance of forgery? that's less than I thought

Would be relatively no trouble to expose this as a configuration item without impacting existing plates; for instance, easiest change would be expanding the range; "harder" change would be to add another config option to allow expansion into higher bases than 10, if the size of the security code was important. E.g. we could do base 62 (lower+upper+numbers) and for the same 4 digits get ~15 million unique values.

**Comment by ttk2** [comment]
what would be the downsides of just expanding the range?

**Comment by ProgrammerDan** [comment]
None really, just would use up more of the lore space, I guess. I'll play
around with it and report back.

**Comment by ProgrammerDan** [comment]
Assign this to me, please

**Comment by Maxopoly** [comment]
Not relevant after rewrite
